/**
 * Interactive CLI setup wizard.
 *
 * Collects credentials, encrypts the private key, writes .env,
 * generates a personality seed, and optionally stores the password
 * in the OS credential store + installs a background service.
 */

import * as readline from 'node:readline';
import { chmodSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { platform } from 'node:os';
import { encryptKey } from '../security/keystore.js';
import { generatePersonalitySeed } from '../marketing/engine.js';
import { resolveDataDir, resolveConfigDir } from '../core/config.js';
import { isCredentialStoreAvailable, storePassword } from './credentials.js';
import { installService } from './service.js';

const DATA_DIR = resolveDataDir();
const KEYFILE_PATH = join(DATA_DIR, 'keyfile.json');
const PERSONALITY_PATH = join(DATA_DIR, 'personality.json');

export async function setup(): Promise<void> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> =>
    new Promise(resolve => rl.question(q, resolve));

  console.log('\n=== EndGame Agent Setup ===\n');

  mkdirSync(DATA_DIR, { recursive: true });

  // Step 1: Private key
  const privateKeyInput = await ask('Paste your Solana private key (base58): ');
  const password = await ask('Choose encryption password for keyfile: ');

  // Decode and encrypt immediately
  const bs58 = (await import('bs58')).default;
  const nacl = await import('tweetnacl');
  let keyBytes: Uint8Array;
  try {
    keyBytes = bs58.decode(privateKeyInput);
  } catch {
    console.error('ERROR: Invalid base58 private key.');
    rl.close();
    process.exit(1);
  }

  // Derive wallet address from key (ed25519 keypair is 64 bytes: secret+public)
  const keypair = keyBytes.length === 64
    ? keyBytes
    : nacl.sign.keyPair.fromSeed(keyBytes.slice(0, 32)).secretKey;
  const publicKey = keypair.slice(32, 64);
  const walletAddress = bs58.encode(publicKey);

  // Encrypt and save keyfile with restrictive permissions
  const keyfile = await encryptKey(keypair, password);
  writeFileSync(KEYFILE_PATH, JSON.stringify(keyfile, null, 2) + '\n');
  chmodSync(KEYFILE_PATH, 0o600);
  console.log(`Keyfile saved to ${KEYFILE_PATH}`);

  // Wipe sensitive data from scope
  keyBytes.fill(0);
  keypair.fill(0);

  // Step 2: Credential store (macOS Keychain / Windows Credential Manager)
  if (isCredentialStoreAvailable()) {
    const useKeychain = (await ask('Store password in system keychain for auto-start? (y/n): ')).trim().toLowerCase();
    if (useKeychain === 'y') {
      if (storePassword(password)) {
        console.log('Password stored securely in system credential store.');
      } else {
        console.log('Failed to store password. You will need to provide it manually.');
      }
    }
  }

  // Step 3: Referral code
  const referralCode = await ask('Your EndGame referral code (optional, press Enter to skip): ');

  // Step 4: LLM provider
  let llmProvider = '';
  while (llmProvider !== 'claude' && llmProvider !== 'openai') {
    llmProvider = (await ask('LLM provider (claude/openai): ')).trim().toLowerCase();
  }
  const llmApiKey = await ask(`${llmProvider} API key: `);
  const llmModel = await ask('Model override (press Enter for default): ');

  // Step 5: Marketing channels
  const enabledChannels: string[] = [];
  const envLines: string[] = [
    `# EndGame Agent config — generated by setup wizard`,
    `WALLET_ADDRESS=${walletAddress}`,
    `KEYFILE_PATH=${KEYFILE_PATH}`,
    `# SECURITY: Password stored in system keychain (or provide at runtime):`,
    `#   KEYFILE_PASSWORD=yourpassword npm start`,
    ``,
    `CLAIM_ENABLED=true`,
    `MARKETING_ENABLED=true`,
    ``,
    `LLM_PROVIDER=${llmProvider}`,
    `LLM_API_KEY=${llmApiKey}`,
  ];
  if (llmModel.trim()) envLines.push(`LLM_MODEL=${llmModel.trim()}`);
  if (referralCode.trim()) envLines.push(`REFERRAL_CODE=${referralCode.trim()}`);
  envLines.push('');

  // Twitter (optional)
  const useTwitter = (await ask('Enable Twitter/X? (y/n): ')).trim().toLowerCase();
  if (useTwitter === 'y') {
    console.log('  Twitter requires a paid Basic tier dev account ($5/month).');
    const apiKey = await ask('  Twitter API Key: ');
    const apiSecret = await ask('  Twitter API Secret: ');
    const accessToken = await ask('  Twitter Access Token: ');
    const accessTokenSecret = await ask('  Twitter Access Token Secret: ');
    envLines.push(`TWITTER_API_KEY=${apiKey}`);
    envLines.push(`TWITTER_API_SECRET=${apiSecret}`);
    envLines.push(`TWITTER_ACCESS_TOKEN=${accessToken}`);
    envLines.push(`TWITTER_ACCESS_TOKEN_SECRET=${accessTokenSecret}`);
    enabledChannels.push('twitter');
  }

  // Discord (optional)
  const useDiscord = (await ask('Enable Discord? (y/n): ')).trim().toLowerCase();
  if (useDiscord === 'y') {
    const webhookUrl = await ask('  Discord Webhook URL: ');
    envLines.push(`DISCORD_WEBHOOK_URL=${webhookUrl}`);
    enabledChannels.push('discord');
  }

  // Telegram (optional)
  const useTelegram = (await ask('Enable Telegram? (y/n): ')).trim().toLowerCase();
  if (useTelegram === 'y') {
    const botToken = await ask('  Telegram Bot Token (from @BotFather): ');
    const chatId = await ask('  Telegram Chat/Channel ID: ');
    envLines.push(`TELEGRAM_BOT_TOKEN=${botToken}`);
    envLines.push(`TELEGRAM_CHAT_ID=${chatId}`);
    enabledChannels.push('telegram');
  }

  if (enabledChannels.length > 0) {
    envLines.push(`MARKETING_CHANNELS=${enabledChannels.join(',')}`);
  } else {
    envLines.push('MARKETING_ENABLED=false');
  }

  // Write .env with restrictive permissions (0600 = owner read/write only)
  const configDir = resolveConfigDir();
  mkdirSync(configDir, { recursive: true });
  const envPath = join(configDir, '.env');
  writeFileSync(envPath, envLines.join('\n') + '\n');
  chmodSync(envPath, 0o600);
  console.log(`Config written to ${envPath}`);

  // Generate personality seed
  const personality = generatePersonalitySeed();
  writeFileSync(PERSONALITY_PATH, JSON.stringify(personality, null, 2) + '\n');
  console.log(`Personality "${personality.name}" saved to ${PERSONALITY_PATH}`);

  // Step 6: Background service
  const installBg = (await ask('Install as background service (starts on login)? (y/n): ')).trim().toLowerCase();
  if (installBg === 'y') {
    let useCaffeinate = false;
    if (platform() === 'darwin') {
      const preventSleep = (await ask('Prevent sleep while agent runs (caffeinate)? (y/n): ')).trim().toLowerCase();
      useCaffeinate = preventSleep === 'y';
    }
    try {
      installService({ useCaffeinate });
      console.log('Background service installed. It will start on next login.');
      console.log('Start now with: endgame-agent start');
    } catch (err) {
      console.log(`Service install failed: ${err instanceof Error ? err.message : String(err)}`);
      console.log('You can start the agent manually with: endgame-agent run');
    }
  }

  console.log(`\nWallet: ${walletAddress}`);
  console.log(`Channels: ${enabledChannels.join(', ') || 'none'}`);
  console.log('\nSetup complete!');
  if (installBg !== 'y') {
    console.log('Start with: endgame-agent start  (or: KEYFILE_PASSWORD=yourpassword endgame-agent run)\n');
  }
  rl.close();
}

// Allow direct execution
setup().catch(err => {
  console.error('Setup failed:', err instanceof Error ? err.message : String(err));
  process.exit(1);
});
